apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: e029732b-f503-499c-b576-e48396a30b64
    subject: chaos-workflow_litmus
    workflow_id: c8027414-9df6-4fa8-ae89-026143bba914
    workflows.argoproj.io/controller-instanceid: e029732b-f503-499c-b576-e48396a30b64
  name: chaos-workflow-1629343020
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  podGC:
    strategy: OnWorkflowCompletion
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: aws-ssm-chaos-by-id
        template: aws-ssm-chaos-by-id
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/aws-ssm-chaos-by-id.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: aws-ssm-chaos-by-id
        path: /tmp/aws-ssm-chaos-by-id.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Execute AWS SSM Chaos on given ec2 instance IDs
            kind: ChaosExperiment
            metadata:
              name: aws-ssm-chaos-by-id
              labels:
                name: aws-ssm-chaos-by-id
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 1.13.8
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                      - batch
                      - litmuschaos.io
                    resources:
                      - jobs
                      - pods
                      - events
                      - pods/log
                      - pods/exec
                      - secrets
                      - configmaps
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:1.13.8
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name aws-ssm-chaos-by-id
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "90"
                  - name: CHAOS_INTERVAL
                    value: "90"
                  - name: RAMP_TIME
                    value: ""
                  - name: EC2_INSTANCE_ID
                    value: ""
                  - name: REGION
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                  - name: DOCUMENT_NAME
                    value: ""
                  - name: DOCUMENT_TYPE
                    value: ""
                  - name: DOCUMENT_FORMAT
                    value: ""
                  - name: DOCUMENT_PATH
                    value: ""
                  - name: INSTALL_DEPENDENCIES
                    value: "True"
                  - name: NUMBER_OF_WORKERS
                    value: "1"
                  - name: MEMORY_PERCENTAGE
                    value: "80"
                  - name: CPU_CORE
                    value: "0"
                  - name: LIB
                    value: litmus
                labels:
                  name: aws-ssm-chaos-by-id
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 1.13.8
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-aws-ssm-chaos-by-id.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: aws-ssm-chaos-by-id
        path: /tmp/chaosengine-aws-ssm-chaos-by-id.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: aws-ssm-chaos-by-id
              labels:
                instance_id: cf336866-534f-408d-a362-bda734536744
                workflow_name: chaos-workflow-1629343020
            spec:
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: aws-ssm-chaos-by-id
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "120"
                        - name: CHAOS_INTERVAL
                          value: "120"
                        - name: EC2_INSTANCE_ID
                          value: i-0a27df2e802610652
                        - name: REGION
                          value: us-west-2
                        - name: MEMORY_PERCENTAGE
                          value: "80"
                        - name: CPU_CORE
                          value: "0"
                        - name: DOCUMENT_NAME
                          value: ""
                        - name: DOCUMENT_TYPE
                          value: ""
                        - name: DOCUMENT_FORMAT
                          value: ""
                        - name: DOCUMENT_PATH
                          value: ""
                        - name: INSTALL_DEPENDENCIES
                          value: "True"
    metadata:
      labels:
        weight: "10"
    name: aws-ssm-chaos-by-id
    outputs: {}
  - arguments: {}
    container:
      args:
      - 'kubectl delete chaosengine -l ''instance_id in (cf336866-534f-408d-a362-bda734536744, )'' -n {{workflow.parameters.adminModeNamespace}} '
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
