apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: e029732b-f503-499c-b576-e48396a30b64
    subject: ec2-terminate-from-hub_litmus
    workflow_id: 2d9660f4-2de4-468b-ac78-0dcfbaf885f3
    workflows.argoproj.io/controller-instanceid: e029732b-f503-499c-b576-e48396a30b64
  name: ec2-terminate-from-hub-1629724247
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: ec2-terminate-by-id
        template: ec2-terminate-by-id
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/ec2-terminate-by-id.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ec2-terminate-by-id
        path: /tmp/ec2-terminate-by-id.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Detaching an ebs volume from ec2 instance.
            kind: ChaosExperiment
            metadata:
              name: ec2-terminate-by-id
              labels:
                name: ec2-terminate-by-id
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 1.13.8
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                      - batch
                      - litmuschaos.io
                    resources:
                      - jobs
                      - pods
                      - events
                      - pods/log
                      - pods/exec
                      - secrets
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                image: litmuschaos/go-runner:1.13.8
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name ec2-terminate-by-id
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "30"
                  - name: CHAOS_INTERVAL
                    value: "30"
                  - name: RAMP_TIME
                    value: ""
                  - name: MANAGED_NODEGROUP
                    value: disable
                  - name: EC2_INSTANCE_ID
                    value: ""
                  - name: REGION
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                  - name: AWS_SHARED_CREDENTIALS_FILE
                    value: /tmp/cloud_config.yml
                  - name: LIB
                    value: litmus
                labels:
                  name: ec2-terminate-by-id
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 1.13.8
                secrets:
                  - name: cloud-secret
                    mountPath: /tmp/
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-ec2-terminate-by-id.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: ec2-terminate-by-id
        path: /tmp/chaosengine-ec2-terminate-by-id.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: ec2-terminate-by-id
              labels:
                instance_id: 89492a58-c0fb-431b-8268-af5f023e7822
                context: ec2-terminate-by-id_litmus
                workflow_name: ec2-terminate-from-hub-1629724247
            spec:
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: ec2-terminate-by-id
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "30"
                        - name: EC2_INSTANCE_ID
                          value: i-0db1ae100c7511211
                        - name: REGION
                          value: us-west-2
                        - name: MANAGED_NODEGROUP
                          value: disable
                    probe:
                      - name: weavesocks-availability-check
                        type: httpProbe
                        mode: Continuous
                        runProperties:
                          probeTimeout: 5
                          retry: 1
                          interval: 5
                          probePollingInterval: 2
                        httpProbe/inputs:
                          url: http://35.81.171.73:30001
                          insecureSkipVerify: false
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
                      - name: weavesocks-perf-mttr-check
                        type: promProbe
                        mode: Edge
                        runProperties:
                          probeTimeout: 2
                          retry: 2
                          interval: 1
                        promProbe/inputs:
                          endpoint: http://44.242.146.190:31090
                          query: sum(rate(request_duration_seconds_count{job='sock-shop/front-end',route='/',status_code='200'}[20s]))*100
                          comparator:
                            type: int
                            criteria: ">="
                            value: "100"
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: ec2-terminate-by-id
    outputs: {}
status:
  finishedAt: null
  startedAt: null
